### ISSUE TITLE
Can't resolve module chart.js compile error

### ISSUE THREAD

**Issue by alpal309** [jhonnold/react-chart.js#1]
My build fails to compile because it can't resolve chart.js in dist/index.js. I've tried uninstalling the package and reinstalling but same error occurs. No changes have been made to the original code.

**Comment by jhonnold** [comment]
What version of `chart.js` have you installed along with the library?

**Comment by alpal309** [comment]
I'm just a moron and didn't install chart.js at all, hence why it couldn't be found. Thank you for clarifying!

**Comment by jhonnold** [comment]
If you continue running into this issue, just make sure you stay on `chart.js^2` - this library currently does not support 3.
